version: "3.1"
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=receipts
    ports:
      - "5432:5432"
    networks:
      - app
  server:
    build: ./server
    restart: always
    command: sh -c "/server/performMigrations.sh && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./server:/server
    environment:
      - POSTGRES_NAME=receipts
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8000:8000"
    networks:
      - app
    depends_on:
      - db

networks:
  app:
    driver: bridge
